# Generated by Django 3.2.6 on 2021-09-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0005_alter_quiz_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='difficulty',
            field=models.CharField(choices=[('fácil', 'fácil'), ('medio', 'medio'), ('alta', 'alta')], max_length=6),
        ),
    ]
